### ISSUE TITLE
After upgrade, magnetic presence is unavailable

### ISSUE THREAD

**Issue by gvala** [petrleocompel/hikaxpro_hacs#10]
First of all thank you for the upgrade!

After upgrading to last version, magnetic presence shows "Unavailable"

The sensor is a Slim Magnetic Contact that was discussed in issue #5.

**Comment by petrleocompel** [comment]
Any logs?

**Comment by gvala** [comment]
The logs I found are the following:


2023-02-27 19:02:35.062 WARNING (SyncWorker_2) [homeassistant.helpers.service] Unable to find services.yaml for the hikvision_axpro integration


This error originated from a custom integration.
Logger: custom_components.hikvision_axpro
Source: custom_components/hikvision_axpro/__init__.py:188
Integration: hikvision_axpro
First occurred: February 27, 2023 at 11:53:24 PM (3 occurrences)
Last logged: 9:31:24 AM
Error getting status: {'SubSysList': [{'SubSys': {'id': 1, 'arming': 'arming', 'alarm': False, 'enabled': True, 'name': 'All', 'delayTime': 25}}, {'SubSys': {'id': 2, 'arming': 'arming', 'alarm': False, 'enabled': True, 'name': 'NoBalcony', 'delayTime': 0}}, {'SubSys': {'id': 3, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 3', 'delayTime': 0}}, {'SubSys': {'id': 4, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 4', 'delayTime': 0}}, {'SubSys': {'id': 5, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 5', 'delayTime': 0}}, {'SubSys': {'id': 6, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 6', 'delayTime': 0}}, {'SubSys': {'id': 7, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 7', 'delayTime': 0}}, {'SubSys': {'id': 8, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 8', 'delayTime': 0}}, {'SubSys': {'id': 9, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 9', 'delayTime': 0}}, {'SubSys': {'id': 10, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 10', 'delayTime': 0}}, {'SubSys': {'id': 11, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 11', 'delayTime': 0}}, {'SubSys': {'id': 12, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 12', 'delayTime': 0}}, {'SubSys': {'id': 13, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 13', 'delayTime': 0}}, {'SubSys': {'id': 14, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 14', 'delayTime': 0}}, {'SubSys': {'id': 15, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 15', 'delayTime': 0}}, {'SubSys': {'id': 16, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 16', 'delayTime': 0}}]}
Error getting status: {'SubSysList': [{'SubSys': {'id': 1, 'arming': 'arming', 'alarm': False, 'enabled': True, 'name': 'All', 'delayTime': 17}}, {'SubSys': {'id': 2, 'arming': 'away', 'alarm': False, 'enabled': True, 'name': 'NoBalcony', 'delayTime': 0}}, {'SubSys': {'id': 3, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 3', 'delayTime': 0}}, {'SubSys': {'id': 4, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 4', 'delayTime': 0}}, {'SubSys': {'id': 5, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 5', 'delayTime': 0}}, {'SubSys': {'id': 6, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 6', 'delayTime': 0}}, {'SubSys': {'id': 7, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 7', 'delayTime': 0}}, {'SubSys': {'id': 8, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 8', 'delayTime': 0}}, {'SubSys': {'id': 9, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 9', 'delayTime': 0}}, {'SubSys': {'id': 10, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 10', 'delayTime': 0}}, {'SubSys': {'id': 11, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 11', 'delayTime': 0}}, {'SubSys': {'id': 12, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 12', 'delayTime': 0}}, {'SubSys': {'id': 13, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 13', 'delayTime': 0}}, {'SubSys': {'id': 14, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 14', 'delayTime': 0}}, {'SubSys': {'id': 15, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 15', 'delayTime': 0}}, {'SubSys': {'id': 16, 'arming': 'disarm', 'alarm': False, 'enabled': False, 'name': 'Περιοχή 16', 'delayTime': 0}}]}

The first one contantly appears and the second appeared after arming the system. Arming worked right.

**Comment by gvala** [comment]
I added this
if zone.zone.detector_type == DetectorType.SLIM_MAGNETIC_CONTACT:
devices.append(HikMagneticContactDetector(coordinator, zone.zone, entry.entry_id))

into sensor.py and now it's OK.
