### ISSUE TITLE
Error to arm | HA 2024.6 compatibility

### ISSUE THREAD

**Issue by infvito** [petrleocompel/hikaxpro_hacs#118]
Arming requires a code but none was given for alarm_control_panel.ax_pro

**Comment by petrleocompel** [comment]
Can you provide  more info ? logs from HomeAssistant ?  Version of HA you are using ? etc ?

**Comment by superbannato** [comment]
I have the same problem.....

HA core 2024.6.2
Supervisor 2024.06.0
OS 12.3

Registratore: homeassistant.components.websocket_api.http.connection
Fonte: components/websocket_api/commands.py:283
Integrazione: Home Assistant WebSocket API (documentazione, problemi)
Prima occorrenza: 11:02:37 (2 occorrenze)
Ultima registrazione: 12:34:09

[545893216560] Arming requires a code but none was given for alarm_control_panel.antifurto
[548009426032] Arming requires a code but none was given for alarm_control_panel.antifurto

**Comment by petrleocompel** [comment]
What FW version do you have on AXPro? 

Was your setup working before the update?

**Comment by superbannato** [comment]
My version of AxPro is V1.2.9 build 240516. Before the last Home Assistant update, it worked perfectly. In the configuration of the add-on (version 2.1.0-beta), I have always set the administrator user as recommended by the documentation. The only thing that works is the alarm disarm function.

**Comment by infvito** [comment]
I can confirm that the problem started after the update.  I have now gone back the version and everything works again

**Comment by superbannato** [comment]
Will this issue be resolved in the next update of the add-on?

**Comment by petrleocompel** [comment]
I have to simulate this problem to fix it.
Also since you commented on issue as I will comment, close or etc you will get notification + I am making released and mentioning it in issues. Sadly due time constraints I will not tell you exact time "when". 

I was looking at updates for HA and saw some redesign for control panels. But did not have time to upgrade yet. 
But 2.1.3 could solve this + one issue with user privilege.

**Comment by superbannato** [comment]
Thank you for your commitment and the work you're doing to fix this issue. I really appreciate your updates and notifications. Good luck with the simulations and the new releases!

**Comment by HOMEGLN** [comment]
More information: https://developers.home-assistant.io/blog/2024/05/22/alarm_control_panel_validation/

**Comment by petrleocompel** [comment]
Temporary fix is done. Currently it should function as before but improvements regarding 2024 versions are not done.

**Comment by petrleocompel** [comment]
[Version released 2.1.3](https://github.com/petrleocompel/hikaxpro_hacs/releases/tag/v2.1.3)

**Comment by petrleocompel** [comment]
Should be resolved. If anything wrong let me know and reopen the issue.
