### ISSUE TITLE
Invalid version number or invalid version installed in Home Assistant

### ISSUE THREAD

**Issue by matias53** [petrleocompel/hikaxpro_hacs#121]
Hi,

I'm quite new to this, so please pardon any mistakes I might be making.

I've just installed the integration with Home Assistant, but I have a question about which version is actually installed.

HACS shows version 2.1.4 (the same as GitHub). I set the custom repository to Home Assistant, which automatically downloaded the integration. However, the version that ends up being installed in Home Assistant is 2.1.0-beta instead of 2.1.4.

I'm not sure if I’m installing it incorrectly, if the version number on the HACS metadata is outdated, or if there’s another issue causing Home Assistant to install the incorrect version.

I followed the installation procedure described here:
https://github.com/petrleocompel/hikaxpro_hacs?tab=readme-ov-file#hacs

Here is Home Assistant Info:
![image](https://github.com/user-attachments/assets/f2ecf2ec-e71f-40eb-89b7-25ff097b02cb)

That's what Home Assistant HACS shows:
![image](https://github.com/user-attachments/assets/bd2cc5a7-b4bd-47c4-a7e0-52725e3ade3b)

What might I be doing wrong? How can I verify which version is actually installed?
Thank you.

**Comment by petrleocompel** [comment]
Fixed and released [Version released 2.1.5](https://github.com/petrleocompel/hikaxpro_hacs/releases/tag/v2.1.5)

**Comment by petrleocompel** [comment]
It was just problem of "displaying it" from manifest
