### ISSUE TITLE
Alarm control unavailable

### ISSUE THREAD

**Issue by favsn** [petrleocompel/hikaxpro_hacs#19]
Hi,

Im trying to install your component but the alarm control is still unavailable. I remove the old version and install the lastest but also the same thing. Can you help me ?

![image](https://user-images.githubusercontent.com/124165026/222659079-12c1b56c-7b78-4709-8991-8c28e0bc1bfc.png)

[home-assistant_hikvision_axpro_2023-03-03T07-17-59.469Z.log](https://github.com/petrleocompel/hikaxpro_hacs/files/10879285/home-assistant_hikvision_axpro_2023-03-03T07-17-59.469Z.log)

**Comment by petrleocompel** [comment]
Released new version this should be fixed if you still have problem then it will be something new again
