### ISSUE TITLE
missing description

### ISSUE THREAD

**Issue by wifi75** [petrleocompel/hikaxpro_hacs#20]
after update to 0.8.1
![image](https://user-images.githubusercontent.com/31816231/222693619-e70a6abd-449b-414b-a461-9cd976635b22.png)

**Comment by DejanBukovec** [comment]
I confirm this.

**Comment by petrleocompel** [comment]
😰 I see what happend currently debugging why.

**Comment by petrleocompel** [comment]
Problem is ... i seems that enties got mixed up :disappointed:

**Comment by petrleocompel** [comment]
Uff ... bug found ... my Init in "zone" mixed up after shuffleling with attributes. In minutes fix will be available

**Comment by wifi75** [comment]
First one Peter!
