### ISSUE TITLE
Magnet Pressence missing

### ISSUE THREAD

**Issue by DejanBukovec** [petrleocompel/hikaxpro_hacs#21]
In 0.8.1 missing "Magnet Presence":
![slika](https://user-images.githubusercontent.com/52787044/222697953-bfd89315-5fa7-48d7-b882-128b78a9f77f.png)

![slika](https://user-images.githubusercontent.com/52787044/222698220-a81facc9-2de4-4bd4-9ccc-3c2016a962ea.png)

**Comment by petrleocompel** [comment]
I understand but sadly it is caused by #20
