### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by DejanBukovec** [petrleocompel/hikaxpro_hacs#23]
Please add under Attributes:
Is via repeater
Alarm
Armed
Stay away

Maybe add also some images that users know what can expect from integration to avoid not working confusions...
Maybe one image for PIR sensor and one image for magnetic sensor...
Magnetic contact:
![slika](https://user-images.githubusercontent.com/52787044/222736534-a881b264-e72b-49cf-ad9a-62012800457e.png)

PIR:
![slika](https://user-images.githubusercontent.com/52787044/222736735-071b50e0-531e-49db-b3be-ace1444052ee.png)

**Comment by petrleocompel** [comment]
After mering #7 system device screenshot will be added too
