### ISSUE TITLE
ADD Repos error

### ISSUE THREAD

**Issue by GGFR-Shawn** [petrleocompel/hikaxpro_hacs#25]
Hello,
I apologize for my English.
When I try to add the repository I have an error see the screenshot.
![Capture d’écran 2023-03-05 111830](https://user-images.githubusercontent.com/9734871/222954580-634d0896-ea2c-4e35-896f-3205671eca16.png)

**Comment by DejanBukovec** [comment]
Hi please read manual:
https://github.com/petrleocompel/hikaxpro_hacs#hacs

You need HACS and istall it inside HACS and not direct in HA ...

**Comment by GGFR-Shawn** [comment]
Really sorry I have two installations of HA, one on raspberry and one on nas synology I thought I had hacs on this machine :( I apologize for the inconvenience

**Comment by GGFR-Shawn** [comment]
it's perfect very sorry for inconvenience
