### ISSUE TITLE
How to integrate ? how to use?

### ISSUE THREAD

**Issue by GGFR-Shawn** [petrleocompel/hikaxpro_hacs#26]
How to integrate and see the sensors of the central hik I'm sorry I'm new in this field I try to understand

**Comment by petrleocompel** [comment]
Can you better explain what do you mean? "central hik" ?
This extension will give you possibility to control AX Pro via HA and read sensors. For adding sensors and full configuration you have to use HikConnect app or Web UI of AX Pro.

**Comment by GGFR-Shawn** [comment]
I am trying to see my devices paired to my ax-pro in home assistant and be able to interact with the alarm without hik connector in local

**Comment by petrleocompel** [comment]
Just install this integration via HACS and that's it.

**Comment by GGFR-Shawn** [comment]
I have installed it but I don't know how and can't find how to add to my Dashboard the entities

**Comment by petrleocompel** [comment]
Did you check in "Devices" integration devices list ?
To add on dashboard it is more generic question  -> https://www.home-assistant.io/dashboards
