### ISSUE TITLE
Brand icons missing

### ISSUE THREAD

**Issue by petrleocompel** [petrleocompel/hikaxpro_hacs#3]
icon missing

![image](https://user-images.githubusercontent.com/31816231/220350931-0a52d719-7225-4c56-96ee-03bdbbe3a7bd.png)

_Originally posted by @wifi75 in https://github.com/petrleocompel/hikaxpro_hacs/issues/2#issuecomment-1438440005_

**Comment by petrleocompel** [comment]
We need to add icon to https://github.com/home-assistant/brands to have it available.

**Comment by wifi75** [comment]
How to install it?

**Comment by petrleocompel** [comment]
We need to wait fro the pull request in home-assistant/brands closed. No need for installation. Then it will automatically display the icon from HA server.

**Comment by petrleocompel** [comment]
https://github.com/home-assistant/brands/pull/4144 is closed we can close issue. Should be online in day

**Comment by wifi75** [comment]
v.0.5.0 
perfect!

thank you

**Comment by petrleocompel** [comment]
@wifi75 upgrade to v0.5.1 there was a bug with status of sensors
