### ISSUE TITLE
DS-KH6320-WTE1 support

### ISSUE THREAD

**Issue by TokarevSergey** [petrleocompel/hikaxpro_hacs#34]
Good afternoon. I have a video intercom panel DS-KH6320-WTE1, it has a built-in alarm system, eight alarm sensors (Zones), two executive relays, four scenes (Home, Away, Vacation, User).
Can I connect to your Homeassistant alarm control integration.
Thank you.

**Comment by petrleocompel** [comment]
There is not a lot information from HikVision if the DS-KH6320-WTE1 supports ISAPI. You can try. 
I suggest use on configuration AX Hub library and enable debug output. 

Basically if you are unable to login to your device via IP on LAN or cannot make the API call, it cannot be supported by this integration. 

If you would provide log I can tell you if there is or is not any hope. 

So far I think DS-KH6320-WTE1 has ISAPI but not sure what methods are implemented and what exactly would be returned.

**Comment by petrleocompel** [comment]
My opinion is not a lot of things will work. You can try. In setup please check AXHub and debugging output and provide output of HomeAssistant.

**Comment by petrleocompel** [comment]
Since there was no more responses I am closing this issue.

Reasons:
- I dont own this device
- No full documentation was provided
