### ISSUE TITLE
new entity in sensors

### ISSUE THREAD

**Issue by youmax01** [petrleocompel/hikaxpro_hacs#35]
Hi!, Is it possible to add one more entity to the motion and door/window sensors?
are a function listed in ISAP .
The ones that appear with the latest implementation are these:
![image](https://user-images.githubusercontent.com/35151341/229869539-3af57add-4832-45c9-a480-9a8be11b0db5.png)

and the one that is missing and is very useful is this:
"status": "breakDown"
"status": "online"

which indicates if the sensor is open or closed, regardless of whether the alarm system is activated

this is two sensors : 8 and 9
sensor 8 is status "online", its ok , close
sensor 9 is status "breakDown" ,this sensor is open position

```json
[{
		"Zone": {
			"id": 8,
			"name": " ventana balcón",
			"status": "online",
			"tamperEvident": false,
			"shielded": false,
			"bypassed": false,
			"armed": false,
			"isArming": false,
			"alarm": false,
			"charge": "normal",
			"signal": 154
		}
	},
	{
		"Zone": {
			"id": 9,
			"name": " ventana cocina",
			"status": "breakDown",
			"tamperEvident": false,
			"shielded": false,
			"bypassed": false,
			"armed": false,
			"isArming": false,
			"alarm": false,
			"charge": "normal",
			"signal": 140
		}
	}
]
 ```

**Comment by petrleocompel** [comment]
It is now implemented. Maybe not great but it reflects the documentation with naming and values for this entitty.

**Comment by youmax01** [comment]
Perfect!, Works great

De: Petr Leo ***@***.***>
Enviado: miércoles, 5 de abril de 2023 03:28
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [petrleocompel/hikaxpro_hacs] new entity in sensors (Issue #35)


It is now implemented. Maybe not great but it reflects the documentation with naming and values for this entity.
