### ISSUE TITLE
Adjustable pull interval

### ISSUE THREAD

**Issue by petrleocompel** [petrleocompel/hikaxpro_hacs#4]
I forgot one more thing, the integration takes place via local ip, but why is it slow in changing state?

_Originally posted by @wifi75 in https://github.com/petrleocompel/hikaxpro_hacs/issues/2#issuecomment-1439635995_

> There is by default a 30 seconds interval defined from HA (can be changed).

**Comment by wifi75** [comment]
update !!
it is this?
![image](https://user-images.githubusercontent.com/31816231/220606360-d1e1ba97-729c-4210-adc2-70238a432207.png)

I tried to change the value to 1, then I re-entered and 30 reappeared. why?

**Comment by wifi75** [comment]
not working...

**Comment by petrleocompel** [comment]
Try currently reload the integration. 
That is might currently problem.

**Comment by wifi75** [comment]
I've done several loads, and I've also rebooted again. but it does not work. the time returns to 30 when you log back into the panel.

**Comment by petrleocompel** [comment]
Fixed labels, fixed save of configuration. I recommend reload of extension after configuration. But not we are good to go. Pulling is configurable.

**Comment by wifi75** [comment]
Pulling is configurable.? What do you want to say?

**Comment by petrleocompel** [comment]
Pull interval - update interval is configurable.

**Comment by wifi75** [comment]
ah yes of course Peter, I already tried it yesterday and it works great.

Thank you!
