### ISSUE TITLE
Beta8 doesn't work

### ISSUE THREAD

**Issue by leciuk81** [petrleocompel/hikaxpro_hacs#42]
HI,
for me always the same errors for all Beta versions. Also now I can no longer install version 1.3.1 which worked for me.
Below is the error received.
Hope you can fix it.
Thank you

![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/126766794/580118f9-0e33-40c1-8227-b00c400b714c)

![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/126766794/8935237e-1c25-4cce-8d6b-0d2d285dfaaf)

![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/126766794/983ecf07-f7c6-45fe-80b3-34b0b8e5a780)

`Logger: homeassistant.config_entries
Source: custom_components/hikvision_axpro/model.py:662
Integration: hikvision_axpro
First occurred: 11:19:59 (2 occurrences)
Last logged: 11:20:53

Error setting up entry Hikvision_axpro_192.168.10.107 for hikvision_axpro
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hikvision_axpro/__init__.py", line 105, in async_setup_entry
    await hass.async_add_executor_job(coordinator.init_device)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hikvision_axpro/__init__.py", line 177, in init_device
    self.load_devices()
  File "/config/custom_components/hikvision_axpro/__init__.py", line 181, in load_devices
    devices = self._load_devices()
  File "/config/custom_components/hikvision_axpro/__init__.py", line 194, in _load_devices
    return ZonesConf.from_dict(response.json())
  File "/config/custom_components/hikvision_axpro/model.py", line 822, in from_dict
    list = from_list(ListElement.from_dict, obj.get("List"))
  File "/config/custom_components/hikvision_axpro/model.py", line 29, in from_list
    return [f(y) for y in x]
  File "/config/custom_components/hikvision_axpro/model.py", line 29, in <listcomp>
    return [f(y) for y in x]
  File "/config/custom_components/hikvision_axpro/model.py", line 806, in from_dict
    zone = ZoneConfig.from_dict(obj.get("Zone"))
  File "/config/custom_components/hikvision_axpro/model.py", line 662, in from_dict
    chime_warning_type = ChimeWarningType(obj.get("chimeWarningType"))
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'continuous' is not a valid ChimeWarningType`

After some time added more errors

![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/126766794/4c6344b8-3bb8-468c-a820-881d58b6b311)

`Logger: custom_components.hikvision_axpro.hikax.hikax
Source: custom_components/hikvision_axpro/hikax/hikax.py:208
Integration: hikvision_axpro
First occurred: 11:28:59 (1 occurrences)
Last logged: 11:28:59

Debug data <SessionLoginCap version="2.0" xmlns="http://www.hikvision.com/ver20/XMLSchema"> <sessionID>7936be44ebdaef3efcb443785042c2be917999626e4948284d66867552681190</sessionID> <challenge>e47a993acf5b7fd7b253fbb4f7ef3624</challenge> <iterations>100</iterations> <isSupportRTSPWithSession>true</isSupportRTSPWithSession> <isIrreversible>true</isIrreversible> <sessionIDVersion>2.1</sessionIDVersion> <salt>3519F0AB7181690F20D90DCCC9EC9239577C5FA5C213048AED81B2AB3BBA8C8E</salt> <salt2>894FC272840644114F489CCBCABFB7BED9F97226E2528C021ABD0321AB6D3421</salt2> </SessionLoginCap>`

`Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.hikvision_axpro.hikax.hikax
Source: custom_components/hikvision_axpro/hikax/hikax.py:93
Integration: hikvision_axpro
First occurred: 11:28:53 (1 occurrences)
Last logged: 11:28:53

Debug data <SessionLoginCap version="2.0" xmlns="http://www.hikvision.com/ver20/XMLSchema"> <sessionID>da1d7a578ee5aa63ddf592894a0d06469e83029fc8977bff7dcf24c8982de3b3</sessionID> <challenge>29d7dac5170e32c2888ce93de3c2dc43</challenge> <iterations>100</iterations> <isSupportRTSPWithSession>true</isSupportRTSPWithSession> <isIrreversible>true</isIrreversible> <sessionIDVersion>2.1</sessionIDVersion> <salt>3519F0AB7181690F20D90DCCC9EC9239577C5FA5C213048AED81B2AB3BBA8C8E</salt> <salt2>894FC272840644114F489CCBCABFB7BED9F97226E2528C021ABD0321AB6D3421</salt2> </SessionLoginCap>`

**Comment by petrleocompel** [comment]
Closed via beta9 - Please report to Beta Feedback issue next time. Do not create extra. I continuously fix problems on betas Via that issue. Each time it can be something different.
