### ISSUE TITLE
Slim magnetic contact not supported

### ISSUE THREAD

**Issue by gvala** [petrleocompel/hikaxpro_hacs#5]
I just installed this integration and I get the above error.
"Logger: homeassistant.helpers.service
Source: helpers/service.py:441
First occurred: 7:06:13 PM (1 occurrences)
Last logged: 7:06:13 PM

Unable to find services.yaml for the hikvision_axpro integration"

**Comment by gvala** [comment]
I also fin this in the logs

This error originated from a custom integration.

Logger: custom_components.hikvision_axpro.model
Source: custom_components/hikvision_axpro/model.py:257
Integration: hikvision_axpro
First occurred: 11:41:28 AM (10 occurrences)
Last logged: 11:43:28 AM

Invalid detector type slimMagneticContact
Detector info: {'id': 0, 'name': 'Main Entrance', 'status': 'online', 'sensorStatus': 'normal', 'magnetOpenStatus': False, 'tamperEvident': False, 'shielded': False, 'bypassed': False, 'armed': False, 'isArming': False, 'alarm': False, 'charge': 'normal', 'signal': 121, 'temperature': 16, 'subSystemNo': 1, 'linkageSubSystem': [1], 'detectorType': 'slimMagneticContact', 'model': '0x00005', 'stayAway': False, 'zoneType': 'Delay', 'isViaRepeater': False, 'zoneAttrib': 'wireless', 'version': 'V1.0.2', 'deviceNo': 2, 'abnormalOrNot': False}

**Comment by gvala** [comment]
I added a few entries in model.py, according to changes in issue 6,
and now the entries are as follows:

class DetectorType(Enum):
    OTHER = "other"
    PASSIVE_INFRARED_DETECTOR = "passiveInfraredDetector"
    WIRELESS_EXTERNAL_MAGNET_DETECTOR = "wirelessExternalMagnetDetector"
    WIRELESS_TEMPERATURE_HUMIDITY_DETECTOR = "wirelessTemperatureHumidityDetector"
    WIRELESS_GLASS_BREAK_DETECTOR = "wirelessGlassBreakDetector"
    WIRELESS_PIR_AM_CURTAIN_DETECTOR = "wirelessDTAMCurtainDetector"
    MAGNETIC_CONTACT = "magneticContact"
    **SLIM_MAGNETIC_CONTACT = "slimMagneticContact"**
    WIRELESS_PIR_CAM_DETECTOR = "pircam"


def detector_model_to_name(model_id: Optional[str]) -> str:
    if model_id == "0x00001":
        return "Passive infrared detector"
    **if model_id == "0x0005":
        return "Slim Magnetic Contact"**
    if model_id == "0x00006":
        return "Magnetic contact"
    if model_id == "0x00012":
        return "Wireless PIR CAM detector"
    if model_id == "0x00018":
        return "Glass break detector"
    if model_id == "0x00026":
        return "Wireless temperature humidity detector"
    if model_id == "0x00028":
        return "Wireless external magnet detector"
    if model_id == "0x00032":
        return "Wireless PIR AM curtain detector"
    if model_id is not None:
        return str(model_id)
    return "Unknown"

The problem is solved!

Please add the changes to the next release

**Comment by DejanBukovec** [comment]
Please try this:
Open file sensor.py and find:
```
            if zone.zone.detector_type == DetectorType.MAGNETIC_CONTACT:
                devices.append(HikMagneticContactDetector(coordinator, zone.zone, entry.entry_id))
```
After this add:
```
            if zone.zone.detector_type == DetectorType.SLIM_MAGNETIC_CONTACT :
                devices.append(HikMagneticContactDetector(coordinator, zone.zone, entry.entry_id))
```

So function will look like:
```
            if zone.zone.detector_type == DetectorType.MAGNETIC_CONTACT:
                devices.append(HikMagneticContactDetector(coordinator, zone.zone, entry.entry_id))
            if zone.zone.detector_type == DetectorType.SLIM_MAGNETIC_CONTACT :
                devices.append(HikMagneticContactDetector(coordinator, zone.zone, entry.entry_id))
            if zone.zone.temperature is not None:
                devices.append(HikTemperature(coordinator, zone.zone, entry.entry_id))
```
I think that this will add you new entity like this:
![slika](https://user-images.githubusercontent.com/52787044/221371710-ac7fcbe4-cbf5-4335-96a9-34965ae70e30.png)

**Comment by gvala** [comment]
Thanks for your help!

I still get this error:
This error originated from a custom integration.

Logger: custom_components.hikvision_axpro.model
Source: custom_components/hikvision_axpro/model.py:264
Integration: hikvision_axpro
First occurred: 7:51:59 AM (16 occurrences)
Last logged: 7:53:29 AM

Invalid detector type slimMagneticContact
Detector info: {'id': 0, 'name': 'Main Entrance', 'status': 'online', 'sensorStatus': 'normal', 'magnetOpenStatus': False, 'tamperEvident': False, 'shielded': False, 'bypassed': False, 'armed': False, 'isArming': False, 'alarm': False, 'charge': 'normal', 'signal': 121, 'temperature': 17, 'subSystemNo': 1, 'linkageSubSystem': [1], 'detectorType': 'slimMagneticContact', 'model': '0x00005', 'stayAway': False, 'zoneType': 'Delay', 'isViaRepeater': False, 'zoneAttrib': 'wireless', 'version': 'V1.0.2', 'deviceNo': 2, 'abnormalOrNot': False}
Detector info: {'id': 1, 'name': 'Warehouse', 'status': 'online', 'sensorStatus': 'normal', 'magnetOpenStatus': False, 'tamperEvident': False, 'shielded': False, 'bypassed': False, 'armed': False, 'isArming': False, 'alarm': False, 'charge': 'normal', 'signal': 121, 'temperature': 16, 'subSystemNo': 1, 'linkageSubSystem': [1, 2], 'detectorType': 'slimMagneticContact', 'model': '0x00005', 'stayAway': False, 'zoneType': 'Instant', 'isViaRepeater': False, 'zoneAttrib': 'wireless', 'version': 'V1.0.2', 'deviceNo': 3, 'abnormalOrNot': False}

All states are shown.
On the other hand, i also have PIR CAM detector and Curtain detector. They also show only temperature an nothing else

**Comment by DejanBukovec** [comment]
This error Invalid detector type slimMagneticContact mean that you don't have DetectorType definition in model.py:
SLIM_MAGNETIC_CONTACT = "slimMagneticContact"
Please check if you have it(If you maybe reload integration in HACS it will be overwritten by original files from github...)
Are this slim magnetic contacts battery powered? Im asking this because information chargeValue is missing which return battery percentage... What version of FW do you run on control panel? I think latest is 1.2.8 build 230110 so maybe is something on that...

About sensors additional informations current release support only Temperature, Humidity and Magnetic options. Maybe in some future release we will receive also battery and signal informations...

**Comment by gvala** [comment]
Ok! One spelling correction and now i can see and the magnet presence for Slim Magnet detector.

The correct entries that need to be inserted are:

SLIM_MAGNETIC_CONTACT = "slimMagneticContact"

if model_id == "0x00005":
        return "Slim Magnetic contact"

if zone.zone.detector_type == DetectorType.SLIM_MAGNETIC_CONTACT:
                devices.append(HikMagneticContactDetector(coordinator, zone.zone, entry.entry_id))

Please add these in the next release!

**Comment by gvala** [comment]
Please add these in the next release!
