### ISSUE TITLE
magnetic contact does not change state

### ISSUE THREAD

**Issue by winniko** [petrleocompel/hikaxpro_hacs#50]
Good morning,

I added add-ons and entered the credentials, it sees me everything.
I can turn the alarm on and off.
But the states of the alarm contact do not change.

Axpro scope 1.0.25, but nothing is working, any ideas?
Thank you
[
![Screenshot (509)](https://github.com/petrleocompel/hikaxpro_hacs/assets/62550328/745f5b0e-4c5e-412b-acec-6534cc939488)
](url)

**Comment by winniko** [comment]
> What version of integration are you using? 
> Are you using AXPro or AXHub? 

Axpro

**Comment by winniko** [comment]
sorry I did not understand , the status changes every 30 seconds? I watched it in RealTime thinking that was the reaction ....

**Comment by petrleocompel** [comment]
Integration is pulling system status (default 30 sec) - configurable in settings. AKA settings "Pull interval".

**Comment by petrleocompel** [comment]
You can set up this pull interval to be 1 second but it might be too much for the system. 
5 seconds can be more reasonable. 

Reason to "pull" is - AXPro does not have any "stream/listenable" API. So we pull data from system.

**Comment by winniko** [comment]
You're right, I put 2 seconds and it's responsive.
but the writings are wrong, and it breaks down

![IMG-20230619-WA0019.jpg](https://github.com/petrleocompel/hikaxpro_hacs/assets/62550328/721c3ae9-134e-4162-b920-804f60180377)

![IMG-20230619-WA0018.jpg](https://github.com/petrleocompel/hikaxpro_hacs/assets/62550328/e56c2889-e140-4af2-8910-1b7d11c90bd7)

**Comment by petrleocompel** [comment]
You can always ask.
Question is
> Is there any way how to get just simple status updates of the devices? Not full state of all device of the system. But basically "on event" the AXPro would call something else? 

The ARC is something like that but we need the update also when alarm is not secured. 

Proper documentation would be amazing...

**Comment by petrleocompel** [comment]
Sadly I cannot make my sensors make working. Tomorrow I am trying again. I will try to give some updates and results.

**Comment by petrleocompel** [comment]
@winniko 
Finally got my sensors working.
It is working, you just have to wait until sync interval (default 30 seconds) 
tested on latest version 2.0.0

![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/9423543/1aeb7848-3a26-4ac6-bc99-3ad3df18f931)

Closing for now. Please confirm if it is working or not. 

We have to look more deeper.
