### ISSUE TITLE
Multiple Areas status not updating

### ISSUE THREAD

**Issue by djb383** [petrleocompel/hikaxpro_hacs#52]
Hello,

Thanks again for all your great work with this project.

I have the "Include areas as separate zones for arm/disarm" enabled and I am using four separate areas.
It seems that only area 1 updates its status to "Armed Home" or "Armed Away".  Areas 2, 3 & 4 remain showing 'disarmed' even though the app confirms they have been armed.

I can still successfully call the service to arm/disarm these individual areas but their status does not update.

I am running v2.0.0-beta13 - AX Pro.
Thanks.

**Comment by djb383** [comment]
I have the interval set to 10 seconds.

There are no errors in the log.  I have attached a capture of the debug log from home assistant.  

My setup has 11 devices (zones), associated with 4 different areas.
The AX Pro is named 'HoneyClaws' (Don't ask ;)
You can see in this screenshot that the Panel and Area 1 show Armed, but the other areas still show disarmed.  They are in fact all armed though, as verified in the HikVision app.
![Screenshot 2023-06-08 225927](https://github.com/petrleocompel/hikaxpro_hacs/assets/72633345/0a88ad70-821b-443c-bb15-a079c3c35a1f)

The log started with the panel disarmed.  Then I did 'Arm Home' followed by a 'Disarm'.  Let me know if you need more info.
[Multiple areas debug.log](https://github.com/petrleocompel/hikaxpro_hacs/files/11688791/Multiple.areas.debug.log)

**Comment by petrleocompel** [comment]
Sadly the debug log yet did not contain "subsystem call" . 

Please try new beta-14 and provide log again.

**Comment by petrleocompel** [comment]
Good at least know where is problem. Now I am going to find out where.

**Comment by petrleocompel** [comment]
Next release will be fixed. beta15 will contain this fix

**Comment by djb383** [comment]
Awesome. Thank you!
