### ISSUE TITLE
version V2.0.1 beta 2 login error on AXhub

### ISSUE THREAD

**Issue by youmax01** [petrleocompel/hikaxpro_hacs#59]
Hi, login errorn in AXhub with version V2.0.1 beta 2 and HA 2023.8.0

Logger: custom_components.hikvision_axpro.hikax.hikax
Source: custom_components/hikvision_axpro/hikax/hikax.py:208
Integration: hikvision_axpro
First occurred: 17:37:16 (4 occurrences)
Last logged: 17:57:23

Debug data <SessionLoginCap version="2.0" xmlns="http://www.hikvision.com/ver20/XMLSchema"> <sessionID>e662a2b75412dc5d59f9</sessionID> <challenge>aa9d917da927f6460f0013c22146aa52</challenge> <iterations>100</iterations> <isSupportRTSPWithSession>true</isSupportRTSPWithSession> </SessionLoginCap>
Debug data <SessionLoginCap version="2.0" xmlns="http://www.hikvision.com/ver20/XMLSchema"> <sessionID>70eff9f5bd8c929e15f0</sessionID> <challenge>d3554b3f52dbe58ebc330f24322f983e</challenge> <iterations>100</iterations> <isSupportRTSPWithSession>true</isSupportRTSPWithSession> </SessionLoginCap>
Debug data <SessionLoginCap version="2.0" xmlns="http://www.hikvision.com/ver20/XMLSchema"> <sessionID>d6e4e6ef1cd225d9a466</sessionID> <challenge>2594637f2b91eb14ef4671564f060ee7</challenge> <iterations>100</iterations> <isSupportRTSPWithSession>true</isSupportRTSPWithSession> </SessionLoginCap>
Debug data <SessionLoginCap version="2.0" xmlns="http://www.hikvision.com/ver20/XMLSchema"> <sessionID>47159f96a1cb3360e724</sessionID> <challenge>8ba2b8f61f3a938ffc1964d5210ab702</challenge> <iterations>100</iterations> <isSupportRTSPWithSession>true</isSupportRTSPWithSession> </SessionLoginCap>

**Comment by pophitru** [comment]
> Hi, login errorn in AXhub with version V2.0.1 beta 2 and HA 2023.8.0
> 
> Logger: custom_components.hikvision_axpro.hikax.hikax Source: custom_components/hikvision_axpro/hikax/hikax.py:208 Integration: hikvision_axpro First occurred: 17:37:16 (4 occurrences) Last logged: 17:57:23
> 
> Debug data e662a2b75412dc5d59f9 aa9d917da927f6460f0013c22146aa52 100 true Debug data 70eff9f5bd8c929e15f0 d3554b3f52dbe58ebc330f24322f983e 100 true Debug data d6e4e6ef1cd225d9a466 2594637f2b91eb14ef4671564f060ee7 100 true Debug data 47159f96a1cb3360e724 8ba2b8f61f3a938ffc1964d5210ab702 100 true

Thanks for the report. As @petrleocompel claims the login issue was fixed in beta2. Will hold on updating.

**Comment by petrleocompel** [comment]
@youmax01 are you sure, you are using latest v2.1.0-beta2?

**Comment by petrleocompel** [comment]
I see. Please from version 2! do not use AXHub configuration option.

**Comment by pophitru** [comment]
beta2 is not yet on HACS repo, mb it takes some time to appear

**Comment by petrleocompel** [comment]
You just need to search for the integration go to its detail and click on `Update information`
<img width="279" alt="image" src="https://github.com/petrleocompel/hikaxpro_hacs/assets/9423543/9b1e9f5b-1689-4370-9166-f3d605d997b7">

**Comment by pophitru** [comment]
> You just need to search for the integration go to its detail and click on `Update information`
> <img alt="image" width="279" src="https://user-images.githubusercontent.com/9423543/257948549-9b1e9f5b-1689-4370-9166-f3d605d997b7.png">

thank you it worked! will try now

**Comment by pophitru** [comment]
Confirm that login issue is fixed! thank you! 
Hope to see sirens in supported devices soon 🙏  did not find siren support in this beta yet

**Comment by petrleocompel** [comment]
@pophitru 
Currently. I added relay support https://github.com/petrleocompel/hikaxpro_hacs/commit/34f770bc32bef71b4f62d057c10e3e3368f8e14e

And tomorrow is test time. And then sirens are going to be next.

**Comment by pophitru** [comment]
good news! I've got AX PRO DS-PS1-I-WE in case you need some testing

**Comment by youmax01** [comment]
> @youmax01 I see. ⚠️ Please from version 2! **do not use AXHub configuration option**. ⚠️
> 
> See changelog of release 2.0.0 <img alt="image" width="956" src="https://user-images.githubusercontent.com/9423543/257947988-e470910a-a822-43a4-9b55-9ef7d5e23ab3.png">

Hi!, yes, beta version is online

![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/35151341/1a29e14e-fa0d-4aba-acd1-d2b10c602935)
y try back to V2.0.3 but dont work either

HA version maybe?, 2023.8.0?

**Comment by youmax01** [comment]
Sorry, back to V2.0.3 and work again!, lastest non beta channel dont.

**Comment by petrleocompel** [comment]
> Sorry, back to V2.0.3 and work again!, lastest non beta channel dont.

Did you uncheck "AXHub" in configuration? From version 2 it is deprecated. Everything works without it.

**Comment by petrleocompel** [comment]
@youmax01  any update ?

**Comment by petrleocompel** [comment]
Closing - inactivity
