### ISSUE TITLE
Add support for multiple Areas

### ISSUE THREAD

**Issue by DejanBukovec** [petrleocompel/hikaxpro_hacs#7]
Hi,

Can you please add support for multiple Area's so option to arm, disarm seperate Area?
For example I have 3 areas.
One area(Garage) is most of time armed and is armed/disarmed seperate of other areas. When I have this area and all other disarmed integration show Disarmed and this is ok:
![slika](https://user-images.githubusercontent.com/52787044/221345484-d6be544e-6feb-43ff-844c-0c92d35fdafc.png)

But when I have garage armed and all other Areas disarmed it show "Armed away" :
![slika](https://user-images.githubusercontent.com/52787044/221345594-63fb37e1-8454-47fe-bf36-4d48a8fe623b.png)

This need to be changed in next way:
- AX PRO Status show general status like in HIK Connect app
- Then under AX PRO are listed Areas with each of them show state and option to change state:
![slika](https://user-images.githubusercontent.com/52787044/221345908-33bf955f-ab9e-4748-b0b8-2e3fe1bc1ba5.png)

**Comment by petrleocompel** [comment]
Problem with this is that HA has Alarm control panel as single entity. https://developers.home-assistant.io/docs/core/entity/alarm-control-panel

We could create multiple of those. I am nof fan of this idea but can be done. I have curently 32 zones... Of course I can add only enabled ones and also it can be optional. I will take a look in next release 0.6.0.

**Comment by petrleocompel** [comment]
Still we need some "main" indicator - example in HikConnect app if any zone is Armed your global state is shown as Armed.
That was the implementation done in https://github.com/gunkutzeybek/hikaxpro_hacs and it was looking on zone 0 as Global.
I changed the behavior to look in every zone and respect it.

I am unsure if we should change it to be optional or should be mandatory to have all zones.
It cannot be implemented as attributes because you could not arm or disarm certain zones.

**Comment by DejanBukovec** [comment]
If understand corectly Zones are Sensors and Areas are "Partitions" So one Zone is one Sensor and one Zone can't have multiple sensors. But Area can have linked multiple sensors. 
For example:
Area: Garage can have linked IR Sensor ID: 1 and Magnetic sensor ID: 2
Area: Floor 1 can have linked IR Sensor ID 3, 4, 5, 6
...

Ok?

So Main alarm control panel entity which is currently used stay as is and will arm/disarm/away ALL Areas. But maybe add additional alarm control panel entities for enabled Areas... Maybe most users have enabled only one Area and it will give them only one... If possible maybe make some setting to list enabled Areas and user select for which one would like to create "alarm control panel entity" but I think this will be more complicated...
I think that seperate Areas and posibility to arm/disarm it will be ok. Maybe one example will be to automaticly arm garage when your car leave home zone in HA...

**Comment by petrleocompel** [comment]
Yes you are right. Sorry for exchaning "zones" with "areas". 

So Area = Alarm Control Panel Entity. And will be created depending on number of "enabled areas" in Hikconnect app.
Main  Alarm Control Panel Entity will remain but it is just cover for all of them.

**Comment by DejanBukovec** [comment]
If Im correct you or gunkutzeybek right now use 0xfffffff to arm/disarm all areas:
![slika](https://user-images.githubusercontent.com/52787044/221766331-aa9f8a66-af1d-40d6-9ab7-924ca2c1172d.png)

I can check documentation to find how request all areas...

**Comment by petrleocompel** [comment]
I know how. `/ISAPI/SecurityCP/status/subSystems` gets all areas.
I is being used https://github.com/petrleocompel/hikaxpro_hacs/blob/88ba3bf472c8399004e535d21239f40b488a94e0/custom_components/hikvision_axpro/__init__.py#L164 
for checking all parts of system. 

I dont know if there is any easy way how to check for "system state" other than going through all sub systems. 
But for multiple control panels it is win because we already fetching all this info.

Also for this there will be need:
* to make it correctly - release new version of `hikaxpro` python depedency with update API for arming and disarming
* hacky way - just place it in project directly

**Comment by wifi75** [comment]
I also have 2 zones, but how do you add the other zone?

**Comment by petrleocompel** [comment]
@wifi75 It was not only me. A lot work was done by @DejanBukovec. 
I just quickly maintain everything. 

But I already started my work on support of multiple areas. We will see how it goes.

**Comment by DejanBukovec** [comment]
Im not sure if using hikaxpro python depedency which is developed by other developer is good way, because you are locked to his work and what he would like to do...

Maybe is best way to use own python dependency or make own class and implement functions which you need...

Yes "GET /ISAPI/SecurityCP/status/subSystems" will return you All Partitions(Areas). Do you have HIK Documentation?
It will return you in JSON:
```
{  
  "SubSysList":[{
/*required, partition list*/
    "SubSys":{
/*optional, partition, it can be set to NULL if partitions are not needed*/
      "id": ,
/*required, int, partition No., which starts from 1*/
      "armType":"",
/*required, string, partition arming type: "stay"-stay arming, "away"-away arming. This node is only valid for arming partitions in a batch*/
      "arming":"", 
/*optional, string, partition arming/disarming status, "stay"-stay arming, "away"-away arming, "disarm"-disarmed, "arming"*/
      "alarm": ,
/*optional, boolean, whether the partition alarm is triggered: true, false*/
      "preventFaultArm": ,
/*optional, boolean, whether to prevent fault arming: true, false*/
      "enabled": ,
/*optional, boolean, whether to enable the partition*/
      "name":"", 
/*optional, string, partition name*/
      "moduleOperateCode":  "12345",
/*optional, string, module operation code, which should be encrypted*/
      "delayTime":  1	
/*optional, int, maximum remaining delay time of the delay zones in the current partition, unit:s; this node is valid when the value of the node arming is "stay" or "away"*/
    }
  }]
}
```

**Comment by petrleocompel** [comment]
I do not have the HIK Documentation all resources are protect by HIK Account login with some extra perms. If you have please provide.

The dependency is actually https://github.com/gunkutzeybek/hikaxpro as original HACS integration. I guess first implementation is going to be "YOLO URL" and lets try to pull request and maintain `hikaxpro` also.

**Comment by DejanBukovec** [comment]
Ok I found public way to get them...

Visit URL:
https://www.hikvision.com/en/support/download/sdk/
Download "Device Network SDK (for Windows 64-bit)" 404MB file. 
Extract it.
Go To "doc" folder and find "Device Network SDK (Security Control)_Developer Guide_V6.1.5.X_20220311.zip" and extract it into some folder. Go to this folder and open index.html :)
Under Appendixes you have Request URIs
![slika](https://user-images.githubusercontent.com/52787044/221900075-e78a3d23-644e-44ff-879f-b7716f76177f.png)

**Comment by petrleocompel** [comment]
Got the linux one. Found it. Nice to have. Much nicer would be to have that directly on the product support page. Not just in their full SDK. Anyway thank you!

**Comment by petrleocompel** [comment]
I have a base implementation 
<img width="759" alt="image" src="https://user-images.githubusercontent.com/9423543/221958949-9e744336-f6e3-4eff-8bd8-df873b469c9d.png">
But need to implement arming and disarming of areas.

**Comment by petrleocompel** [comment]
It is implemented, not great. Would be nice to manually test it. Currently I cannot modify running system. I am offsite.
If you @DejanBukovec go for it (manually install) use branch (7-add-support-for-multiple-areas)[https://github.com/petrleocompel/hikaxpro_hacs/tree/7-add-support-for-multiple-areas]

**Comment by petrleocompel** [comment]
For better implementation we have to wait for merge of gunkutzeybek/hikaxpro#11 and release of new version.

**Comment by DejanBukovec** [comment]
Hi,
I will test it this weekend.
Thanks.

**Comment by wifi75** [comment]
how to proceed to alarm only one area?

**Comment by wifi75** [comment]
spectacular I would say!
you're too strong Petr

**Comment by DejanBukovec** [comment]
Is this already fully implemented in latest release? If yes then it do not work ok.
I have armed-away area with name "Garaža" but in HA it show as unarmed...
![slika](https://user-images.githubusercontent.com/52787044/224482336-3aba189c-4386-41d7-885f-caaa540a410e.png)

After reload integration with debugging enabled it show correct state:
![slika](https://user-images.githubusercontent.com/52787044/224482530-c48c208f-2ace-4fd0-b4b4-15f9ffc1d249.png)

I will try leave debugging enabled and see if it will be reproduced...

**Comment by petrleocompel** [comment]
Did you wait the pull interval time? It takes time to update this info. 

It was prepared for testing a week. I just decided to add it as optional so if there is something wrong it can be disabled. 

I am unsure about sorting. I don't think we have control over it.

**Comment by wifi75** [comment]
oh yes installation occured !

but on config it is correct like below ?

```
 [[SeasonsReport]]
        # The SeasonsReport uses the 'Seasons' skin, which contains the
        # images, templates and plots for the report.
        skin = Seasons
        enable = true
    
    [[SmartphoneReport]]
        # The SmartphoneReport uses the 'Smartphone' skin, and the images and
        # files are placed in a dedicated subdirectory.
        skin = Smartphone
        enable = false
        HTML_ROOT = /var/www/html/weewx/smartphone
    
    [[MobileReport]]
        # The MobileReport uses the 'Mobile' skin, and the images and files
        # are placed in a dedicated subdirectory.
        skin = Mobile
        enable = false
        HTML_ROOT = /var/www/html/weewx/mobile
    
    [[StandardReport]]
        # This is the old "Standard" skin. By default, it is not enabled.
        skin = Standard
        enable = true
   
    [[WdcReport]]
        lang = en
        enable = true
        skin = weewx-wdc
```

**Comment by petrleocompel** [comment]
@wifi75 Are you sure you are replying on correct issue?

**Comment by wifi75** [comment]
ohhhhhhhhh sorry....!!!

**Comment by DejanBukovec** [comment]
Yes Im few minutes(I have interval 10 seconds), but ther has not be any line about axpro... Now over night has been debugging enabled and after Im disable it it download me log file but there has not be any log line about axpro inside it...

**Comment by petrleocompel** [comment]
That is really strange I have to say: please try it again.

- Restart HA
- enable logging
- activate zone
- wait pull internaval
- deactivate zone
- wait pull internval
- disable logging
- provide logs
