### ISSUE TITLE
lovelace control panel theme

### ISSUE THREAD

**Issue by wifi75** [petrleocompel/hikaxpro_hacs#78]
hi, in my alarm control unit I have created 2 zones for different purposes, home assistant I have these two tabs, but they are very uncomfortable to see, could it be possible to have the states in a single tab?
![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/31816231/fc67ffd6-3597-485e-90d5-4cd152c91599)

![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/31816231/9e45dc85-496a-490b-ba5b-eecc2de3ae5a)

**Comment by petrleocompel** [comment]
Can you explain little bit more? 

Sadly this has nothing to do with the integration. 
You can disable zones and control the system as 1 unit. 
Or just make your own "dashboard cards". Templates and etc.... 

You do not have to use code. You can use button with state. Theme is not topic of this integration. 
Lovelace themes are point of presentation of data and controls.

Example
![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/9423543/af0510d3-7587-45e0-931e-5ec1e0261c40)
