### ISSUE TITLE
Warning in logs

### ISSUE THREAD

**Issue by gvala** [petrleocompel/hikaxpro_hacs#8]
I get this warning on boot:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 8:44:22 AM (1 occurrences)
Last logged: 8:44:22 AM

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for hikvision_axpro using this method at custom_components/hikvision_axpro/__init__.py, line 99: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by DejanBukovec** [comment]
This can be fixed by editing file __init__.py and inside function async_setup_entry
Find:
`    hass.config_entries.async_setup_platforms(entry, PLATFORMS)`

Replace it with:
`    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)`

**Comment by gvala** [comment]
Thanks! It worked!
