### ISSUE TITLE
Is this integration still working?

### ISSUE THREAD

**Issue by dedgedesign** [petrleocompel/hikaxpro_hacs#86]
Hello,
I am not a Home Assistant power user but this integration is giving me some doubts.
I have installed it using HACS (no issue whatsoever) but when I go to Settings > Devices & Services I do not see it (of course Home Assistant has been restarted...)
My Home Assistant is Supervised (it is on a Proxmox VM), actual version is 2024.1.3 : is this installation supported? I have tried the 2.1.0beta15 and the master version without any improvement.
What do I miss?

**Comment by petrleocompel** [comment]
Did you check logs ? 
I will upgrade my instance from 2023.12.1 to 2024.X now. But Yes I personally use it everyday.

**Comment by petrleocompel** [comment]
I am going to release 2.1.0-beta15 as full version 2.1.0 soon as I upgrade my instance.

**Comment by petrleocompel** [comment]
Have you added "integration" and configure it ?

**Comment by dedgedesign** [comment]
Hello, I do not see any log as the integration does not appear anywhere!

It is effectively downloaded as you can see from HACS :
￼

But is not visible in the Integration list :
￼

No trace at all in my list of entities or devices…

Home Assistant logs does say anything special except the non surprising warning below :

024-01-17 20:04:05.472 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hikvision_axpro which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant


This installation is nearly new, so I do not think anything is making any conflicts.

**Comment by petrleocompel** [comment]
Since you replied via email your pictures are not visible.

**Comment by petrleocompel** [comment]
Currently I updated my instance to 2024.1.3

And integration is clearly there. 
<img width="506" alt="image" src="https://github.com/petrleocompel/hikaxpro_hacs/assets/9423543/21d00617-13d9-4fd8-bfc8-991e58471da1">

**Comment by dedgedesign** [comment]
Hello, I do not see any log as the integration does not appear anywhere!

It is effectively downloaded as you can see from HACS :
￼
<img width="531" alt="Capture d’écran 2024-01-17 à 20 05 54" src="https://github.com/petrleocompel/hikaxpro_hacs/assets/156458925/6636ba56-afb8-40a9-98f5-8867f259f047">


But is not visible in the Integration list :
￼
<img width="1882" alt="Capture d’écran 2024-01-17 à 20 06 53" src="https://github.com/petrleocompel/hikaxpro_hacs/assets/156458925/f97e1359-b1b6-42e0-83eb-baf80478fc3c">


No trace at all in my list of entities or devices…

Home Assistant logs does say anything special except the non surprising warning below :

024-01-17 20:04:05.472 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hikvision_axpro which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant


This installation is nearly new, so I do not think anything is making any conflicts.

**Comment by petrleocompel** [comment]
In bottom right you have to "Add integration"
<img width="1258" alt="image" src="https://github.com/petrleocompel/hikaxpro_hacs/assets/9423543/bc9ad92c-4b76-4c96-9b4b-56b6be81bfc6">

**Comment by dedgedesign** [comment]
So we can close this...
