### ISSUE TITLE
Connection using node red

### ISSUE THREAD

**Issue by vishnup3211** [petrleocompel/hikaxpro_hacs#87]
while trying to get the current status of a alarm sensor using current status node, even if the state is changing no output is  coming from the node

**Comment by vishnup3211** [comment]
Node red add-on in home assistant
Also node red companion using hacs
All entities are coming in node red and I can get status using a poll state node 
But current status node is not outputting any changes..

**Comment by petrleocompel** [comment]
Sadly I still do not see any connection between your use case and "this" integration.

**Comment by petrleocompel** [comment]
This integration ends in home assistant. If anything between "homeassistant" and "node-red" does not work it is not problem of this integration. Clearly there is some miss configuration of your "node-red". 

If you see data in HomeAssistant from this integration.. it works.

**Comment by Drealine** [comment]
I can't have log in HA. I'm enable debug log in your integration. Maybe missing option ?

**Comment by petrleocompel** [comment]
@Drealine how does that connect to "node-red" ?

**Comment by vishnup3211** [comment]
i got it working, i get the status when i use event state node.
thanks for the support
