### ISSUE TITLE
No entities or device found on DS-PWA96-M2H-WE 

### ISSUE THREAD

**Issue by Luke95vl** [petrleocompel/hikaxpro_hacs#94]
Hi everyone, I'm trying to integrate my DS-PWA96-M2H-WE control panel, I tried to authenticate with the hikconnect data, I also tried them from the control panel's web interface and they work without problems. I've tried all configurations but I always get the error that it doesn't find any devices or entities.

[home-assistant_hikvision_axpro_2024-02-01T10-20-13.518Z.log](https://github.com/petrleocompel/hikaxpro_hacs/files/14123906/home-assistant_hikvision_axpro_2024-02-01T10-20-13.518Z.log)

**Comment by petrleocompel** [comment]
It is an error. Some sensors are unknown or entities because AX docs are very "vague" and miss a lot of types and docs. 

Will be fixed as hotfix

**Comment by petrleocompel** [comment]
Fixed with [v2.1.1](https://github.com/petrleocompel/hikaxpro_hacs/releases/tag/v2.1.1)

Can happen that some problems will be there still (different devices / undocumented types) just reopen the issue.
