### ISSUE TITLE
AXHub Magnet presence

### ISSUE THREAD

**Issue by HOMEGLN** [petrleocompel/hikaxpro_hacs#95]
Hello! I have a Hikvision Axhub and after the upgrade from V2.1.0-beta 15 to beta 16 or v2.1.1 I miss the sensors that indicate whether the magnetic contacts are open or closed. the entity that shows this is no longer available according to HA.

I have 3 magnetic contacts and the status is no longer visible on all of them. When I downgrade to beta 15 they are available again.

![Magnet error](https://github.com/petrleocompel/hikaxpro_hacs/assets/97314456/8bfa0cad-9395-4441-8a94-a859b895bb1b)

**Comment by petrleocompel** [comment]
Could you please enable debug output in configuration of integration, restart HA, wait for pull interval and provide logs of that? 
Also what model of magnetic sensors do you have?

**Comment by HOMEGLN** [comment]
[home-assistant_hikvision_axpro_2024-02-04T21-50-29.430Z.log](https://github.com/petrleocompel/hikaxpro_hacs/files/14158620/home-assistant_hikvision_axpro_2024-02-04T21-50-29.430Z.log)

**Comment by HOMEGLN** [comment]
Type of magnetic sensor is Hikvision DS-PD1-MC-WWS. Thanks!

**Comment by petrleocompel** [comment]
Went back to some issues with "magnets" since some fixing some issues. 
Sadly "AX" systems "AX Hub" system does not send "magnet" status.  Same as dont sent battery level. Just "low battery" sensor.

"AX Pro" sends these values.

Logs from you confirms that.

**Comment by HOMEGLN** [comment]
Hello @petrleocompel,

In version 2.1.0-beta15 it does. See screenshot. It stopped working in version 2.1.0-beta16 and later.

![image](https://github.com/user-attachments/assets/03964a39-f7ee-43b5-82d4-bffad848cd54)

**Comment by petrleocompel** [comment]
I understand. But Magnet presence was never really working for these systems. Because the system does not send the value. 
Also you are behind a releases. take a look - https://github.com/petrleocompel/hikaxpro_hacs/releases

**Comment by petrleocompel** [comment]
It was basically issue where "magnet entity" is added because "detector" is type "magnet" and the check for "is on?" was checking status instead the real value of magnet.

So... it was not working. 

If you can simulate that value changes I would love to see logs before and after triggering the sensor. 
(even if you install new version the logs will still see this changes in any case. Also keep in mind your pull interval of data)

**Comment by petrleocompel** [comment]
Does not matter. Just dont forget in configuration of integration enable debug output. Then restart HA and then enable debugging of integration.

**Comment by petrleocompel** [comment]
I was going through old logs @HOMEGLN 

<img width="963" alt="image" src="https://github.com/user-attachments/assets/f1ebc494-48c3-447b-80e8-f86202053e6e">

All the time magnet info is not being sent. 

If you will have logs please put them here. And possibly mark some timestamps when did magnet open and closed. 

Also what is your update interval in settings ?

**Comment by HOMEGLN** [comment]
Here is the logging of version 2.1.0-beta 15 in which the magnetic contact information is working. I opened the door at 20:39:41 hours where the status immediately jumps from "magnet presence" on to off. 

Door open: 20:39:41
Door closed: 20:39.49 
Door open: 20:39:55 
Door closed: 20.40.01 

The door is called "voordeur". 

"achterdeur" and "Raam woonkamer" are also magnetic contacts. But I didn't open or close those magnet contacts in this logging

The magnetic contacts therefore work properly and indicate exactly whether the door is open or closed. So it is not incorrect information that the sensor displays, but matches the actual situation with the door and is also updated immediately when the door is opened or closed

Hopefully you can find something and fix the problem in the new versions so that I can update again and not have to get stuck on 2.1.0-beta 15.

The update interval is set to 1

[home-assistant_hikvision_axpro_2025-01-12T19-40-24.231Z - Working.log](https://github.com/user-attachments/files/18390994/home-assistant_hikvision_axpro_2025-01-12T19-40-24.231Z.-.Working.log)

P.s. I have also tested the latest version but the problem is still present.

**Comment by petrleocompel** [comment]
The update interval is set to 1 can cause extreme troubles. 
You can absolutely wreck your system.
